### ISSUE TITLE
Could you get a license for this project?

### ISSUE THREAD

**Issue by mingtaozhangsc** [Abnaxos/gradle-preshadow-plugin#2]
Hi, @Abnaxos 

I really like your work on top of shadow plugin. Is it possible to get a apache license on this project?

Thanks in advance!

Best Regards,
Mingtao

**Comment by Abnaxos** [comment]
It's MIT-Licensed. The MIT license is actually _less_ restrictive than the Apache license. So feel free to do whatever you'd like to do.
